apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator
subjects:
  - kind: ServiceAccount
    name: prometheus-operator
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: prometheus-operator
  apiGroup: rbac.authorization.k8s.io