apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-monitoring
  namespace: monitoring
spec:
  replicas: 1
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: monitoring
  ruleSelector:
    matchLabels:
      team: monitoring
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: alertmanager-operated
        port: 9093
        scheme: http
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
  storage:
    volumeClaimTemplate:
      metadata:
        name: prometheus-pvc
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: nfs
        resources:
          requests:
            storage: 30Gi