apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: monitoring-rules
  namespace: monitoring
  labels:
    team: monitoring
spec:
  groups:
    - name: node
      rules:
        - alert: NodePingFailed
          expr: probe_success{job="blackbox-ping"} == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Node {{ $labels.instance }} is not responding to ping"
            description: "Node {{ $labels.instance }} has failed to respond to ICMP ping for more than 5 minutes"
    - name: certificates
      rules:
        - alert: SSLCertExpiringSoon
          expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30 and on(instance) (probe_http_ssl{job!="blackbox-local"} == 1)
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "SSL certificate expiring soon for {{ $labels.instance }}"
            description: "SSL certificate for {{ $labels.instance }} expires in less than 30 days"
    - name: website
      rules:
        - alert: WebsiteDown
          expr: probe_success{job!="blackbox-ping"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Website {{ $labels.instance }} is down"
            description: "Website {{ $labels.instance }} has been down for more than 5 minutes"
    - name: proxmox-cpu
      rules:
        - alert: NodeHighCPU
          expr: avg by(id) (pve_cpu_usage_ratio{id=~"node/.*"} * 100) * on(id) group_left(name, instance) pve_node_info > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage for node {{ $labels.name }}"
            description: "Node {{ $labels.name }} with IP {{ $labels.instance }} is using more than 80% CPU"
        - alert: LxcHighCPU
          expr: avg by(id) (pve_cpu_usage_ratio{id=~"lxc/.*"} * 100) * on(id) group_left(name, node) pve_guest_info{type="lxc"} > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage for LXC {{ $labels.name }}"
            description: "LXC {{ $labels.name }} on node {{ $labels.node }} is using more than 80% CPU"
        - alert: VmHighCPU
          expr: avg by(id) (pve_cpu_usage_ratio{id=~"qemu/.*"} * 100) * on(id) group_left(name, node) pve_guest_info{type="qemu"} > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage for VM {{ $labels.name }}"
            description: "VM {{ $labels.name }} on node {{ $labels.node }} is using more than 80% CPU"
    - name: proxmox-memory
      rules:
        - alert: NodeHighMemory
          expr: (avg by (id) (pve_memory_usage_bytes{id=~"node/.*"} /1024/1024/1024) > avg by (id) (pve_memory_size_bytes{id=~"node/.*"} / 1024 / 1024 / 1024 / 100 * 80)) * on(id) group_left(name, instance) pve_node_info
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High Memory usage for node {{ $labels.name }}"
            description: "Node {{ $labels.name }} with IP {{ $labels.instance }} is using more than 80% Memory"
        - alert: LxcHighMemory
          expr: (avg by (id) (pve_memory_usage_bytes{id=~"lxc/.*"} /1024/1024/1024) > avg by (id) (pve_memory_size_bytes{id=~"lxc/.*"} / 1024 / 1024 / 1024 / 100 * 80)) * on(id) group_left(name, node) pve_guest_info{type="lxc"}
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High Memory usage for LXC {{ $labels.name }}"
            description: "LXC {{ $labels.name }} on node {{ $labels.node }} is using more than 80% Memory"
        - alert: VmHighMemory
          expr: (avg by (id) (pve_memory_usage_bytes{id=~"qemu/.*"} /1024/1024/1024) > avg by (id) (pve_memory_size_bytes{id=~"qemu/.*"} / 1024 / 1024 / 1024 / 100 * 80)) * on(id) group_left(name, node) pve_guest_info{type="qemu"}
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High Memory usage for VM {{ $labels.name }}"
            description: "VM {{ $labels.name }} on node {{ $labels.node }} is using more than 80% Memory"
    - name: proxmox-offline
      rules:
        - alert: NodeOffline
          expr: pve_up{id=~"node/.*"} * on(id) group_left(name, instance) pve_node_info == 0
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Node {{ $labels.name }} offline"
            description: "Node {{ $labels.name }} with IP {{ $labels.instance }} is offline"
        - alert: LxcOffline
          expr: pve_up{id=~"lxc/.*"} * on(id) group_left(name, node) pve_guest_info{type="lxc"} == 0
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "LXC {{ $labels.name }} offline"
            description: "LXC {{ $labels.name }} on node {{ $labels.node }} is offline"
        - alert: VmOffline
          expr: pve_up{id=~"qemu/.*"} * on(id) group_left(name, node) pve_guest_info{type="qemu"} == 0
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "VM {{ $labels.name }} offline"
            description: "VM {{ $labels.name }} on node {{ $labels.node }} is offline"
        - alert: StorageOffline
          expr: pve_up{id=~"storage/.*"} * on(id) group_left(storage, node) pve_storage_info == 0
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Storage {{ $labels.name }} offline"
            description: "Storage {{ $labels.name }} on node {{ $labels.node }} is offline"
    - name: kubernetes-pods
      rules:
        - alert: PodCrashLooping
          expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
          for: 3m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.exported_container }} is crash looping"
            description: "Pod {{ $labels.exported_pod }} in namespace {{ $labels.exported_namespace }} is crash looping"
        - alert: PodNotReady
          expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown"}) > 0
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.exported_container }} not ready"
            description: "Pod {{ $labels.exported_pod }} in namespace {{ $labels.exported_namespace }} has been in a non-ready state for more than 15 minutes"
        - alert: ContainerHighMemory
          expr: sum by(namespace, pod) (container_memory_usage_bytes) > 1.5 * 1024 * 1024 * 1024
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage for pod {{ $labels.exported_container }}"
            description: "Pod {{ $labels.exported_pod }} in namespace {{ $labels.exported_namespace }} is using more than 1.5GB of memory"
        - alert: ContainerHighCPU
          expr: sum by(namespace, pod) (rate(container_cpu_usage_seconds_total[5m])) > 0.8
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage for pod {{ $labels.exported_container }}"
            description: "Pod {{ $labels.exported_pod }} in namespace {{ $labels.exported_namespace }} is using more than 80% CPU"
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: blackbox-targets
  namespace: monitoring
  labels:
    team: monitoring
spec:
  groups:
    - name: blackbox
      interval: 30s
      rules:
        - record: probe_success
          expr: probe_success{job="blackbox"}
