apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: monitoring-rules
  namespace: monitoring
  labels:
    team: monitoring
spec:
  groups:
    - name: node
      rules:
        - alert: HostDown
          expr: up == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Host {{ $labels.instance }} is down"
            description: "{{ $labels.instance }} has been down for more than 5 minutes."
    - name: certificates
      rules:
        - alert: SSLCertExpiringSoon
          expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "SSL certificate expiring soon for {{ $labels.instance }}"
            description: "SSL certificate for {{ $labels.instance }} expires in less than 30 days"
    - name: website
      rules:
        - alert: WebsiteDown
          expr: probe_success == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Website {{ $labels.instance }} is down"
            description: "Website {{ $labels.instance }} has been down for more than 5 minutes"
    - name: kubernetes-pods
      rules:
        - alert: PodCrashLooping
          expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.pod }} is crash looping"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is crash looping"
        - alert: PodNotReady
          expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown"}) > 0
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.pod }} not ready"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has been in a non-ready state for more than 15 minutes"
        - alert: ContainerHighMemory
          expr: sum by(namespace, pod) (container_memory_usage_bytes) > 1.5 * 1024 * 1024 * 1024
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage for pod {{ $labels.pod }}"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is using more than 1.5GB of memory"
        - alert: ContainerHighCPU
          expr: sum by(namespace, pod) (rate(container_cpu_usage_seconds_total[5m])) > 0.8
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage for pod {{ $labels.pod }}"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is using more than 80% CPU"