apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: monitoring-rules
  namespace: monitoring
  labels:
    team: monitoring
spec:
  groups:
    - name: node
      rules:
        - alert: NodePingFailed
          expr: probe_success{job="blackbox-ping"} == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Node {{ $labels.instance }} is not responding to ping"
            description: "Node {{ $labels.instance }} has failed to respond to ICMP ping for more than 5 minutes"
    - name: certificates
      rules:
        - alert: SSLCertExpiringSoon
          expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30 and on(instance) (probe_http_ssl{job!="blackbox-local"} == 1)
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "SSL certificate expiring soon for {{ $labels.instance }}"
            description: "SSL certificate for {{ $labels.instance }} expires in less than 30 days"
    - name: website
      rules:
        - alert: WebsiteDown
          expr: probe_success{job!="blackbox-ping"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Website {{ $labels.instance }} is down"
            description: "Website {{ $labels.instance }} has been down for more than 5 minutes"
    - name: kubernetes-pods
      rules:
        - alert: PodCrashLooping
          expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
          for: 3m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.exported_container }} is crash looping"
            description: "Pod {{ $labels.exported_pod }} in namespace {{ $labels.exported_namespace }} is crash looping"
        - alert: PodNotReady
          expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown"}) > 0
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.exported_container }} not ready"
            description: "Pod {{ $labels.exported_pod }} in namespace {{ $labels.exported_namespace }} has been in a non-ready state for more than 15 minutes"
        - alert: ContainerHighMemory
          expr: sum by(namespace, pod) (container_memory_usage_bytes) > 1.5 * 1024 * 1024 * 1024
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage for pod {{ $labels.exported_container }}"
            description: "Pod {{ $labels.exported_pod }} in namespace {{ $labels.exported_namespace }} is using more than 1.5GB of memory"
        - alert: ContainerHighCPU
          expr: sum by(namespace, pod) (rate(container_cpu_usage_seconds_total[5m])) > 0.8
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage for pod {{ $labels.exported_container }}"
            description: "Pod {{ $labels.exported_pod }} in namespace {{ $labels.exported_namespace }} is using more than 80% CPU"
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: blackbox-targets
  namespace: monitoring
  labels:
    team: monitoring
spec:
  groups:
    - name: blackbox
      interval: 30s
      rules:
        - record: probe_success
          expr: probe_success{job="blackbox"}
