apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: monitoring
type: Opaque
stringData:
  prometheus-additional.yaml: |
    - job_name: 'blackbox-https'
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
          - https://ha.wiserisk.be
          - https://plex.wiserisk.be/identity
          - https://qbittorrent.wiserisk.be
          - https://seedbox.wiserisk.be
          - https://hermes.wiserisk.be
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter.monitoring.svc.cluster.local:9115
    - job_name: 'blackbox-basic-auth'
      metrics_path: /probe
      params:
        module: [http_2xx_basic_auth]
      static_configs:
        - targets:
          - https://webhook.wiserisk.be
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter.monitoring.svc.cluster.local:9115
    - job_name: 'blackbox-local'
      metrics_path: /probe
      params:
        module: [http_2xx_insecure]
      static_configs:
        - targets:
          - https://flash.ilo.wiserisk.home
          - https://ha.wiserisk.home
          - https://adguard.wiserisk.home
          - https://pbs.wiserisk.home
          - https://plex.wiserisk.home/identity
          - https://pve.wiserisk.home
          - https://flash.pve.wiserisk.home
          - https://wasp.pve.wiserisk.home
          - https://adminer.wiserisk.home/adminer
          - https://qbittorrent.wiserisk.home
          - https://seedbox.wiserisk.home
          - https://traefik.wiserisk.home
          - https://hermes.wiserisk.home
          - https://webhook.wiserisk.home
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter.monitoring.svc.cluster.local:9115
    - job_name: 'blackbox-ping'
      metrics_path: /probe
      params:
        module: [icmp]
      static_configs:
        - targets:
          - 10.0.0.1
          - 10.0.0.80
          - 10.0.0.81
          - 10.0.0.82
          - 10.0.0.85
          - 10.0.0.86
          - 10.0.0.95
          - 10.100.0.1
          - 10.100.0.10
          - 10.100.0.103
          - 10.100.0.105
          - 10.100.0.106
          - 10.100.0.151
          - 10.100.0.152
          - 10.100.0.153
          - 10.100.0.200
          - 10.100.0.201
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter.monitoring.svc.cluster.local:9115