apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: monitoring
type: Opaque
stringData:
  prometheus-additional.yaml: |
    - job_name: 'jellyfin'
      metrics_path: /metrics
      scheme: https
      static_configs:
        - targets:
          - jellyfin.wiserisk.be
    - job_name: 'blackbox-https'
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
          - https://ha.wiserisk.be
          - https://jellyfin.wiserisk.be/health
          - https://seedbox.wiserisk.be
          - https://hermes.wiserisk.be
          - https://argocd.k3s.wiserisk.be
          - https://registry.k3s.wiserisk.be
          - https://vault.k3s.wiserisk.be
          - https://grafana.k3s.wiserisk.be
          - https://tautulli.k3s.wiserisk.be
          - https://flaresolverr.k3s.wiserisk.be
          - https://graylog.k3s.wiserisk.be
          - https://librespeed.k3s.wiserisk.be
          - https://nextcloud.k3s.wiserisk.be
          - https://portainer.k3s.wiserisk.be
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter.monitoring.svc.cluster.local:9115
    - job_name: 'blackbox-basic-auth'
      metrics_path: /probe
      params:
        module: [http_2xx_basic_auth]
      static_configs:
        - targets:
          - https://webhook.wiserisk.be
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter.monitoring.svc.cluster.local:9115
    - job_name: 'blackbox-local'
      metrics_path: /probe
      params:
        module: [http_2xx_insecure]
      static_configs:
        - targets:
          - https://flash.ilo.wiserisk.home
          - https://ha.wiserisk.home
          - https://adguard.wiserisk.home
          - https://pbs.wiserisk.home
          - https://jellyfin.wiserisk.home/health
          - https://pve.wiserisk.home
          - https://flash.pve.wiserisk.home
          - https://qbittorrent.wiserisk.home
          - https://seedbox.wiserisk.home
          - https://traefik.wiserisk.home
          - https://hermes.wiserisk.home
          - https://webhook.wiserisk.home
          - https://registry-ui.k3s.wiserisk.home
          - https://traefik.k3s.wiserisk.home
          - https://alertmanager.k3s.wiserisk.home
          - https://blackbox.k3s.wiserisk.home
          - https://ksm.k3s.wiserisk.home
          - https://prometheus.k3s.wiserisk.home
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter.monitoring.svc.cluster.local:9115
    - job_name: 'blackbox-ping'
      metrics_path: /probe
      params:
        module: [icmp]
      static_configs:
        - targets:
          - 10.0.0.1
          - 10.0.0.80
          - 10.0.0.81
          - 10.0.0.85
          - 10.0.0.86
          - 10.0.0.95
          - 10.100.0.1
          - 10.100.0.10
          - 10.100.0.103
          - 10.100.0.105
          - 10.100.0.151
          - 10.100.0.152
          - 10.100.0.201
          - 10.100.0.202
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter.monitoring.svc.cluster.local:9115
    - job_name: 'pve'
      static_configs:
        - targets:
          - 10.0.0.81
      metrics_path: /pve
      params:
        module: [default]
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: proxmox-exporter.monitoring.svc.cluster.local:9221