apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config
  namespace: monitoring
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_status_codes: [200]
          preferred_ip_protocol: ip4
          fail_if_ssl: false
          fail_if_not_ssl: true
          tls_config:
            insecure_skip_verify: false
      http_2xx_basic_auth:
        prober: http
        timeout: 5s
        http:
          valid_status_codes: [200]
          preferred_ip_protocol: ip4
          fail_if_ssl: false
          fail_if_not_ssl: true
          tls_config:
            insecure_skip_verify: false
          basic_auth:
            username: <path:k3s/data/global#basic_username>
            password: <path:k3s/data/global#basic_password>
      http_2xx_insecure:
        prober: http
        timeout: 5s
        http:
          valid_status_codes: [200]
          preferred_ip_protocol: ip4
          fail_if_ssl: false
          fail_if_not_ssl: false
          tls_config:
            insecure_skip_verify: true
      icmp:
        prober: icmp
        timeout: 5s
        icmp:
          preferred_ip_protocol: ip4