apiVersion: v1
kind: ConfigMap
metadata:
  name: hlabmonitor-config
data:
  application.yaml: |
    springdoc:
      swagger-ui:
        enabled: true
    database:
      type: sqlite
    debug:
      controller:
        enabled: true
    monitoring:
      notification:
        enabled: false
        email:
          enabled: true
          from: <path:k3s/data/monitoring#email>
          to: <path:k3s/data/monitoring#email>
          smtp:
            host: smtp.gmail.com
            port: 587
            username: <path:k3s/data/monitoring#email>
            password: <path:k3s/data/monitoring#email_password>
            auth: true
            tls: true
          firing: true
          resolved: false
          failed: false
        discord:
          enabled: false
          webhookUrl: <path:k3s/data/monitoring#discord>
          firing: true
          resolved: true
          failed: true
        telegram:
          enabled: false
          token: <path:k3s/data/monitoring#telegram_token>
          chatId: <path:k3s/data/monitoring#telegram_chatid>
          firing: true
          resolved: true
          failed: true
        log:
          enabled: true
          level: ERROR
          firing: true
          resolved: true
          failed: true
      ping:
        router:
          target: 10.0.0.1
        pbs:
          target: 10.0.0.80
        flash-pve:
          target: 10.0.0.81
        ha:
          target: 10.0.0.95
        traefik:
          target: 10.0.0.85
        traefik-100:
          target: 10.100.0.1
        hermes:
          target: 10.100.0.10
        qbittorrent:
          target: 10.100.0.105
        k3s-master:
          target: 10.100.0.151
        k3s-worker-01:
          target: 10.100.0.152
        seedbox:
          target: 10.100.0.201
        jellyfin:
          target: 10.100.0.202
        tailscale:
          target: 10.100.0.220
      http:
        ha:
          target: https://ha.wiserisk.be
        jellyfin:
          target: https://jellyfin.wiserisk.be/health
        seedbox:
          status-code: 429
          target: https://seedbox.wiserisk.be/login
        hermes:
          target: https://hermes.wiserisk.be/ui/
        argocd:
          target: https://argocd.k3s.wiserisk.be
        registry:
          target: https://registry.k3s.wiserisk.be
        vault:
          target: https://vault.k3s.wiserisk.be/ui/
        grafana:
          target: https://grafana.k3s.wiserisk.be/login
        flaresolverr:
          target: https://flaresolverr.k3s.wiserisk.be
        graylog:
          target: https://graylog.k3s.wiserisk.be
        librespeed:
          target: https://librespeed.k3s.wiserisk.be
        nextcloud:
          target: https://nextcloud.k3s.wiserisk.be/login
        portainer:
          target: https://portainer.k3s.wiserisk.be
        flash-ilo-local:
          internal: true
          target: https://flash.ilo.wiserisk.home
          certificate:
            verify: false
        ha-local:
          internal: true
          target: https://ha.wiserisk.home
          certificate:
            verify: false
        adguard-local:
          internal: true
          target: https://adguard.wiserisk.home
          certificate:
            verify: false
        pbs-local:
          internal: true
          target: https://pbs.wiserisk.home
          certificate:
            verify: false
        jellyfin-local:
          internal: true
          target: https://jellyfin.wiserisk.home/health
          certificate:
            verify: false
        pve-local:
          internal: true
          target: https://pve.wiserisk.home
          certificate:
            verify: false
        flash-pve-local:
          internal: true
          target: https://flash.pve.wiserisk.home
          certificate:
            verify: false
        qbittorrent-local:
          internal: true
          target: https://qbittorrent.wiserisk.home
          certificate:
            verify: false
        seedbox-local:
          internal: true
          status-code: 429
          target: https://seedbox.wiserisk.home/login
          certificate:
            verify: false
        traefik-local:
          internal: true
          target: https://traefik.wiserisk.home
          certificate:
            verify: false
        hermes-local:
          internal: true
          target: https://hermes.wiserisk.home
          certificate:
            verify: false
        webhook-local:
          internal: true
          target: https://webhook.wiserisk.home
          certificate:
            verify: false
        registry-ui-local:
          internal: true
          target: https://registry-ui.k3s.wiserisk.home
          certificate:
            verify: false
        traefik-k3s-local:
          internal: true
          target: https://traefik.k3s.wiserisk.home
          certificate:
            verify: false
        alertmanager-local:
          internal: true
          target: https://alertmanager.k3s.wiserisk.home
          certificate:
            verify: false
        blackbox-local:
          internal: true
          target: https://blackbox.k3s.wiserisk.home
          certificate:
            verify: false
        ksm-local:
          internal: true
          target: https://ksm.k3s.wiserisk.home
          certificate:
            verify: false
        prometheus-local:
          internal: true
          target: https://prometheus.k3s.wiserisk.home
          certificate:
            verify: false