apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hlabmonitor-pvc
  namespace: hlabmonitor
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi