---
# Gatus — monitoring uptime interne — LXC 1102 (10.100.0.102) sur Wasp

# https://github.com/TwiN/gatus/releases
gatus_version: "5.35.0"
gatus_port: 8080
gatus_discord_webhook: "{{ vault_gatus_discord_webhook }}"
gatus_basic_auth:
  user: monitoring
  password: "{{ vault_gatus_monitor_password }}"

gatus_endpoints:
  # K3S — raison d'être de ce Gatus (monitoring de secours si K3S est down)
  - name: K3S API
    url: "tcp://10.100.0.151:6443"
    interval: 1m
  # K3S — raison d'être de ce Gatus (monitoring de secours si K3S est down)
  - name: FLash
    url: "tcp://10.0.0.81:8006"
    interval: 1m
  # VPS
  - name: VPS (public)
    url: "https://gatus.vps.wiserisk.be"
    interval: 5m
    expected_status: 200

hardening_ufw_rules:
  - port: "8080"
    proto: tcp
    rule: allow
