---
# qBittorrent — LXC 1106 (10.100.0.106)
# NFS SeedBox : /mnt/pve/SeedBox → /media/seedbox
#
# VPN futur : WireGuard pré-installé, configurer /etc/wireguard/wg0.conf au moment voulu

qbittorrent_webui_port: 8090

hardening_ufw_rules:
  - port: "8090"
    proto: tcp
    rule: allow
  - port: "6881"
    proto: tcp
    rule: allow
  - port: "6881"
    proto: udp
    rule: allow