http:
  services:
    gitea:
      loadBalancer:
        servers:
          - url: "http://10.100.0.100:3000"

  routers:
    gitea:
      rule: "Host(`git.wiserisk.be`) || Host(`git.wiserisk.home`)"
      entryPoints:
        - "web"
      middlewares:
        - "redirect-to-https@file"
      service: "noop@internal"
    gitea-secure:
      rule: "Host(`git.wiserisk.be`)"
      entryPoints:
        - "websecure"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "gitea@file"
      tls:
        certResolver: letsencrypt-ecdsa
        options: mintls13
    gitea-local-secure:
      rule: "Host(`git.wiserisk.home`)"
      entryPoints:
        - "websecure"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "gitea@file"
      tls: {}