http:
  services:
    ha:
      loadBalancer:
        servers:
          - url: "http://10.0.0.95:8123"

  routers:
    ha:
      rule: "Host(`ha.wiserisk.be`) || Host(`ha.wiserisk.home`)"
      entryPoints:
        - "web"
      middlewares:
        - "redirect-to-https@file"
      service: "noop@internal"
    ha-secure:
      rule: "Host(`ha.wiserisk.be`)"
      entryPoints:
        - "websecure"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "ha@file"
      tls:
        certResolver: letsencrypt-ecdsa
        options: mintls13
    ha-local-secure:
      rule: "Host(`ha.wiserisk.home`)"
      entryPoints:
        - "websecure"
      middlewares:
        - "security@file"
        - "compression@file"
        - "ha-headers@file"
      service: "ha@file"
      tls: {}