http:
  services:
    k3s-wildcard:
      loadBalancer:
        servers:
          - url: "http://10.100.0.151"
  routers:
    # Trafic .be reçu en plain HTTP depuis Edge (TLS terminé au VPS)
    k3s-wildcard-be:
      rule: "HostRegexp(`.*\\.k3s\\.wiserisk\\.be`) || Host(`k3s.wiserisk.be`)"
      entryPoints:
        - "web"
      service: "k3s-wildcard@file"
      priority: 2
    # Trafic .home : TLS terminé ici, forwarding HTTP vers K3S
    k3s-wildcard-home:
      rule: "HostRegexp(`.*\\.k3s\\.wiserisk\\.home`) || Host(`k3s.wiserisk.home`)"
      entryPoints:
        - "websecure"
      service: "k3s-wildcard@file"
      priority: 2
      tls: {}

tcp:
  services:
    k3s-management-tcp:
      loadBalancer:
        servers:
          - address: "10.100.0.151:6443"

  routers:
    k3s-management-tcp:
      rule: "HostSNI(`*`)"
      entryPoints:
        - "k3s"
      service: "k3s-management-tcp@file"

udp:
  routers:
    graylog-udp:
      entrypoints:
        - graylog
      service: graylog-udp
  services:
    graylog-udp:
      loadbalancer:
        servers:
          - address: 10.100.0.151:12201
          - address: 10.100.0.152:12201