http:
  services:
    k3s-wildcard:
      loadBalancer:
        servers:
          - url: "http://10.100.0.151"
          - url: "http://10.100.0.152"
          - url: "http://10.100.0.153"
  routers:
    k3s-wildcard:
      rule: "HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.k3s.wiserisk.be`) || Host(`k3s.wiserisk.be`)"
      entryPoints:
        - "web"
      service: "k3s-wildcard@file"
      priority: 2
    k3s-wildcard-acme:
      rule: "HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.k3s.wiserisk.be`) && PathPrefix(`/.well-known/acme-challenge/`) || Host(`k3s.wiserisk.be`) && PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - "web"
      service: "k3s-wildcard@file"
      priority: 1001

tcp:
  services:
    k3s-secure-wildcard-tcp:
      loadBalancer:
        servers:
          - address: "10.100.0.151:443"
          - address: "10.100.0.152:443"
          - address: "10.100.0.153:443"
    k3s-management-tcp:
      loadBalancer:
        servers:
          - address: "10.100.0.151:6443"
          - address: "10.100.0.152:6443"
          - address: "10.100.0.153:6443"

  routers:
    k3s-secure-wildcard-tcp:
      rule: "HostSNIRegexp(`{subdomain:[a-zA-Z0-9-]+}.k3s.wiserisk.be`) || HostSNI(`k3s.wiserisk.be`)"
      entryPoints:
        - "websecure"
      service: "k3s-secure-wildcard-tcp@file"
      priority: 2
      tls:
        passthrough: true
    k3s-local-wildcard-tcp:
      rule: "HostSNIRegexp(`{subdomain:[a-zA-Z0-9-]+}.k3s.wiserisk.local`) || HostSNI(`k3s.wiserisk.local`)"
      entryPoints:
        - "web"
      service: "k3s-secure-wildcard-tcp@file"
      priority: 2
    k3s-management-tcp:
      rule: "HostSNI(`*`)"
      entryPoints:
        - "k3s"
      service: "k3s-management-tcp@file"