http:
  services:
    k3s-wildcard:
      loadBalancer:
        servers:
          - url: "http://{{ip.k3s.1}}"
          - url: "http://{{ip.k3s.2}}"
          - url: "http://{{ip.k3s.3}}"
  routers:
    k3s-wildcard:
      rule: "HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.{{domain.k3s}}`) || Host(`{{domain.k3s}}`)"
      entryPoints:
        - "web"
      service: "k3s-wildcard@file"
      priority: 2
    k3s-wildcard-acme:
      rule: "HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.{{domain.k3s}}`) && PathPrefix(`/.well-known/acme-challenge/`) || Host(`{{domain.k3s}}`) && PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - "web"
      service: "k3s-wildcard@file"
      priority: 1001

tcp:
  services:
    k3s-secure-wildcard-tcp:
      loadBalancer:
        servers:
          - address: "{{ip.k3s.1}}:443"
          - address: "{{ip.k3s.2}}:443"
          - address: "{{ip.k3s.3}}:443"
    k3s-management-tcp:
      loadBalancer:
        servers:
          - address: "{{ip.k3s.1}}:6443"
          - address: "{{ip.k3s.2}}:6443"
          - address: "{{ip.k3s.3}}:6443"

  routers:
    k3s-secure-wildcard-tcp:
      rule: "HostSNIRegexp(`{subdomain:[a-zA-Z0-9-]+}.{{domain.k3s}}`) || HostSNI(`{{domain.k3s}}`)"
      entryPoints:
        - "websecure"
      service: "k3s-secure-wildcard-tcp@file"
      priority: 2
      tls:
        passthrough: true
    k3s-management-tcp:
      rule: "HostSNI(`*`)"
      entryPoints:
        - "k3s"
      service: "k3s-management-tcp@file"