http:
  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://10.100.0.103:80"
  routers:
    nextcloud:
      rule: "Host(`nextcloud.wiserisk.be`)"
      entryPoints:
        - "web"
      service: "nextcloud@file"
      priority: 2
    nextcloud-acme:
      rule: "Host(`nextcloud.wiserisk.be`) && PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - "web"
      service: "nextcloud@file"
      priority: 1001

tcp:
  services:
    nextcloud-secure-tcp:
      loadBalancer:
        servers:
          - address: "10.100.0.103:443"
  routers:
    nextcloud-secure-tcp:
      rule: "HostSNI(`nextcloud.wiserisk.be`)"
      entryPoints:
        - "websecure"
      service: "nextcloud-secure-tcp@file"
      priority: 2
      tls:
        passthrough: true