http:
  services:
    ollama:
      loadBalancer:
        servers:
          - url: "http://10.100.0.104:11434"

  routers:
    ollama:
      rule: "Host(`ollama.wiserisk.be`)"
      entryPoints:
        - "web"
      middlewares:
        - "ollama-bearer@file"
        - "security@file"
        - "compression@file"
      service: "ollama@file"
    ollama-home:
      rule: "Host(`ollama.wiserisk.home`)"
      entryPoints:
        - "web"
      middlewares:
        - "redirect-to-https@file"
      service: "noop@internal"
    ollama-secure-local:
      rule: "Host(`ollama.wiserisk.home`)"
      entryPoints:
        - "websecure"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "ollama@file"
      tls: {}