http:
  services:
    pbs:
      loadBalancer:
        servers:
          - url: "http://10.0.0.80:8007"
  routers:
    pbs-local:
      rule: "Host(`pbs.wiserisk.home`)"
      entryPoints:
        - "web"
      middlewares:
        - "redirect-to-https@file"
      service: "noop@internal"

tcp:
  services:
    pbs-secure-tcp:
      loadBalancer:
        servers:
          - address: "10.0.0.80:8007"
  routers:
    pbs-secure-local-tcp:
      rule: "HostSNI(`pbs.wiserisk.home`)"
      entryPoints:
        - "websecure"
      service: "pbs-secure-tcp@file"
      priority: 2
      tls:
        passthrough: true