http:
  routers:
    traefik-local:
      rule: "Host(`flash.pbs.wiserisk.home`)"
      entryPoints:
        - "web"
      middlewares:
        - "redirect-to-https@file"
      service: "noop@internal"

tcp:
  services:
    flash-pbs-secure-tcp:
      loadBalancer:
        servers:
          - address: "10.100.0.109:8007"
  routers:
    flash-pbs-secure-local-tcp:
      rule: "HostSNI(`flash.pbs.wiserisk.be`)"
      entryPoints:
        - "websecure"
      service: "flash-pbs-secure-tcp@file"
      priority: 2
      tls:
        passthrough: true