http:
  services:
    plex:
      loadBalancer:
        servers:
          - url: "http://10.100.0.104:32400"

  routers:
    plex:
      rule: "Host(`plex.wiserisk.be`)"
      entryPoints:
        - "web"
      middlewares:
        - "redirect-to-https@file"
      service: "noop@internal"
    plex-secure:
      rule: "Host(`plex.wiserisk.be`)"
      entryPoints:
        - "websecure"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "plex@file"
      tls:
        certResolver: letsencrypt-ecdsa
        options: mintls13
    plex-local:
      rule: "Host(`plex.wiserisk.local`)"
      entryPoints:
        - "web"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "plex@file"

tcp:
  services:
    plex-tcp:
      loadBalancer:
        servers:
          - address: "10.100.0.104:32400"

  routers:
    plex-tcp:
      rule: "HostSNI(`*`)"
      entryPoints:
        - "plex"
      service: "plex-tcp@file"