http:
  services:
    portainer-wildcard:
      loadBalancer:
        servers:
          - url: "http://10.100.0.101"
  routers:
    portainer-wildcard:
      rule: "HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.portainer.wiserisk.be`) || Host(`portainer.wiserisk.be`)"
      entryPoints:
        - "web"
      service: "portainer-wildcard@file"
      priority: 2
    portainer-wildcard-acme:
      rule: "HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.portainer.wiserisk.be`) && PathPrefix(`/.well-known/acme-challenge/`) || Host(`portainer.wiserisk.be`) && PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - "web"
      service: "portainer-wildcard@file"
      priority: 1001

tcp:
  services:
    portainer-secure-wildcard-tcp:
      loadBalancer:
        servers:
          - address: "10.100.0.101:443"

  routers:
    portainer-secure-wildcard-tcp:
      rule: "HostSNIRegexp(`{subdomain:[a-zA-Z0-9-]+}.portainer.wiserisk.be`) || HostSNI(`portainer.wiserisk.be`)"
      entryPoints:
        - "websecure"
      service: "portainer-secure-wildcard-tcp@file"
      priority: 2
      tls:
        passthrough: true