http:
  services:
    adminer:
      loadBalancer:
        servers:
          - url: "http://10.100.0.106/adminer"

  routers:
    adminer:
      rule: "Host(`adminer.wiserisk.home`)"
      entryPoints:
        - "web"
      middlewares:
        - "redirect-to-https@file"
      service: "noop@internal"
    adminer-secure-local:
      rule: "Host(`adminer.wiserisk.home`)"
      entryPoints:
        - "websecure"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "adminer@file"
      tls: {}

tcp:
  services:
    postgres-tcp:
      loadBalancer:
        servers:
          - address: "10.100.0.106:5432"

  routers:
    postgres-tcp:
      rule: "HostSNI(`postgres.wiserisk.be`)"
      entryPoints:
        - "postgres"
      service: "postgres-tcp@file"