http:
  routers:
    pve-local:
      rule: "Host(`pve.wiserisk.home`) || Host(`flash.pve.wiserisk.home`) || Host(`wasp.pve.wiserisk.home`)"
      entryPoints:
        - "web"
      middlewares:
        - "redirect-to-https@file"
      service: "noop@internal"

tcp:
  services:
    pve-secure-tcp:
      loadBalancer:
        servers:
          - address: "10.0.0.82:8006"
          - address: "10.0.0.81:8006"
    flash-pve-secure-tcp:
      loadBalancer:
        servers:
          - address: "10.0.0.81:8006"
    wasp-pve-secure-tcp:
      loadBalancer:
        servers:
          - address: "10.0.0.82:8006"
  routers:
    pve-secure-local-tcp:
      rule: "HostSNI(`pve.wiserisk.home`)"
      entryPoints:
        - "websecure"
      service: "pve-secure-tcp@file"
      priority: 2
      tls:
        passthrough: true
    flash-pve-secure-local-tcp:
      rule: "HostSNI(`flash.pve.wiserisk.home`)"
      entryPoints:
        - "websecure"
      service: "flash-pve-secure-tcp@file"
      priority: 2
      tls:
        passthrough: true
    wasp-pve-secure-local-tcp:
      rule: "HostSNI(`wasp.pve.wiserisk.home`)"
      entryPoints:
        - "websecure"
      service: "wasp-pve-secure-tcp@file"
      priority: 2
      tls:
        passthrough: true