http:
  services:
    pve:
      loadBalancer:
        serversTransport: pve-transport
        servers:
          - url: "https://10.0.0.80:8006"
          - url: "https://10.0.0.81:8006"
    thor:
      loadBalancer:
        serversTransport: thor-transport
        servers:
          - url: "https://10.0.0.80:8006"
    flash:
      loadBalancer:
        serversTransport: flash-transport
        servers:
          - url: "https://10.0.0.81:8006"

  routers:
    pve:
      rule: "Host(`pve.wiserisk.local`)"
      entryPoints:
        - "web"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "pve@file"
    thor:
      rule: "Host(`thor.pve.wiserisk.local`)"
      entryPoints:
        - "web"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "thor@file"
    flash:
      rule: "Host(`flash.pve.wiserisk.local`)"
      entryPoints:
        - "web"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "flash@file"

  serversTransports:
    pve-transport:
      insecureSkipVerify: true
    thor-transport:
      insecureSkipVerify: true
    flash-transport:
      insecureSkipVerify: true