http:
  services:
    seedbox:
      loadBalancer:
        servers:
          - url: "http://10.100.0.105:80"
  routers:
    seedbox:
      rule: "Host(`seedbox.wiserisk.be`)"
      entryPoints:
        - "web"
      service: "noop@internal"
      priority: 2
    seedbox-acme:
      rule: "Host(`seedbox.wiserisk.be`) && PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - "web"
      service: "seedbox@file"
      priority: 1001

tcp:
  services:
    seedbox-secure-tcp:
      loadBalancer:
        servers:
          - address: "10.100.0.105:443"
  routers:
    seedbox-secure-tcp:
      rule: "HostSNI(`seedbox.wiserisk.be`)"
      entryPoints:
        - "websecure"
      service: "seedbox-secure-tcp@file"
      priority: 2
      tls:
        passthrough: true
    seedbox-local-tcp:
      rule: "HostSNI(`seedbox.wiserisk.home`)"
      entryPoints:
        - "web"
      service: "seedbox-secure-tcp@file"
      priority: 2
      tls:
        passthrough: true