http:
  services:
    swizzin:
      loadBalancer:
        servers:
          - url: "http://{{ip.swizzin}}:80"
  routers:
    swizzin:
      rule: "Host(`{{domain.swizzin}}`)"
      entryPoints:
        - "web"
      service: "noop@internal"
      priority: 2
    swizzin-acme:
      rule: "Host(`{{domain.swizzin}}`) && PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - "web"
      service: "swizzin@file"
      priority: 1001

tcp:
  services:
    swizzin-secure-tcp:
      loadBalancer:
        servers:
          - address: "{{ip.swizzin}}:443"
  routers:
    swizzin-secure-tcp:
      rule: "HostSNI(`{{domain.swizzin}}`)"
      entryPoints:
        - "websecure"
      service: "swizzin-secure-tcp@file"
      priority: 2
      tls:
        passthrough: true