http:
  services:
    swizzin:
      loadBalancer:
        servers:
          - url: "http://10.100.0.105:80"
  routers:
    swizzin:
      rule: "Host(`swizzin.wiserisk.be`)"
      entryPoints:
        - "web"
      service: "noop@internal"
      priority: 2
    swizzin-acme:
      rule: "Host(`swizzin.wiserisk.be`) && PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - "web"
      service: "swizzin@file"
      priority: 1001

tcp:
  services:
    swizzin-secure-tcp:
      loadBalancer:
        servers:
          - address: "10.100.0.105:443"
  routers:
    swizzin-secure-tcp:
      rule: "HostSNI(`swizzin.wiserisk.be`)"
      entryPoints:
        - "websecure"
      service: "swizzin-secure-tcp@file"
      priority: 2
      tls:
        passthrough: true