http:
  services:
    hermes-syncthing:
      loadBalancer:
        servers:
          - url: "http://10.100.0.10:20910"
    hades-syncthing:
      loadBalancer:
        servers:
          - url: "http://10.100.0.220:8081"

  routers:
    hermes-syncthing:
      rule: "Host(`hermes.syncthing.wiserisk.be`) || Host(`hermes.syncthing.wiserisk.home`)"
      entryPoints:
        - "web"
      middlewares:
        - "redirect-to-https@file"
      service: "noop@internal"
    hermes-syncthing-secure:
      rule: "Host(`hermes.syncthing.wiserisk.be`)"
      entryPoints:
        - "websecure"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "hermes-syncthing@file"
      tls:
        certResolver: letsencrypt-ecdsa
        options: mintls13
    hermes-syncthing-secure-local:
      rule: "Host(`hermes.syncthing.wiserisk.home`)"
      entryPoints:
        - "websecure"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "hermes-syncthing@file"
      tls: {}
    hades-syncthing:
      rule: "Host(`hades.syncthing.wiserisk.be`) || Host(`hades.syncthing.wiserisk.home`)"
      entryPoints:
        - "web"
      middlewares:
        - "redirect-to-https@file"
      service: "noop@internal"
    hade-syncthings-secure:
      rule: "Host(`hades.syncthing.wiserisk.be`)"
      entryPoints:
        - "websecure"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "hades-syncthing@file"
      tls:
        certResolver: letsencrypt-ecdsa
        options: mintls13
    hades-syncthing-secure-local:
      rule: "Host(`hades.syncthing.wiserisk.home`)"
      entryPoints:
        - "websecure"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "hades-syncthing@file"
      tls: { }