http:
  services:
    traefik:
      loadBalancer:
        servers:
          - url: "http://localhost:8080"

  routers:
    traefik-local:
      rule: "Host(`traefik.wiserisk.home`)"
      entryPoints:
        - "web"
      middlewares:
        - "redirect-to-https@file"
      service: "noop@internal"
    traefik-secure-local:
      rule: "Host(`traefik.wiserisk.home`)"
      entryPoints:
        - "websecure"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "api@internal"