http:
  services:
    traefik:
      loadBalancer:
        servers:
          - url: "http://localhost:8080"

  routers:
    traefik:
      rule: "Host(`{{domain.traefik}}`)"
      entryPoints:
        - "web"
      middlewares:
        - "redirect-to-https@file"
      service: "noop@internal"
    traefik-secure:
      rule: "Host(`{{domain.traefik}}`)"
      entryPoints:
        - "websecure"
      middlewares:
        - "my-auth@file"
        - "security@file"
        - "compression@file"
      service: "api@internal"
      tls:
        certResolver: letsencrypt-ecdsa
        options: mintls13