http:
  services:
    hermes:
      loadBalancer:
        servers:
          - url: "http://10.100.0.10"
    hades:
      loadBalancer:
        servers:
          - url: "http://10.100.0.220:8080"

  routers:
    hermes:
      rule: "Host(`hermes.wiserisk.be`)"
      entryPoints:
        - "web"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "hermes@file"
    hermes-home:
      rule: "Host(`hermes.wiserisk.home`)"
      entryPoints:
        - "web"
      middlewares:
        - "redirect-to-https@file"
      service: "noop@internal"
    hermes-secure-local:
      rule: "Host(`hermes.wiserisk.home`)"
      entryPoints:
        - "websecure"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "hermes@file"
      tls: {}
    hades:
      rule: "Host(`hades.wiserisk.be`)"
      entryPoints:
        - "web"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "hades@file"
    hades-home:
      rule: "Host(`hades.wiserisk.home`)"
      entryPoints:
        - "web"
      middlewares:
        - "redirect-to-https@file"
      service: "noop@internal"
    hades-secure-local:
      rule: "Host(`hades.wiserisk.home`)"
      entryPoints:
        - "websecure"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "hades@file"
      tls: {}