http:
  services:
    nas:
      loadBalancer:
        servers:
          - url: "http://10.100.0.106"

  routers:
    nas:
      rule: "Host(`truenas.wiserisk.be`)"
      entryPoints:
        - "web"
      middlewares:
        - "redirect-to-https@file"
      service: "noop@internal"
    nas-secure:
      rule: "Host(`truenas.wiserisk.be`)"
      entryPoints:
        - "websecure"
      middlewares:
        - "security@file"
        - "compression@file"
      service: "nas@file"
      tls:
        certResolver: letsencrypt-ecdsa
        options: mintls13