http:
  routers:
    wazuh-local:
      rule: "Host(`wazuh.wiserisk.home`) || Host(`wazuh.wiserisk.be`)"
      entryPoints:
        - "web"
      middlewares:
        - "redirect-to-https@file"
      service: "noop@internal"

tcp:
  services:
    wazuh-1515:
      loadBalancer:
        servers:
          - address: "10.100.0.2:1515"
    wazuh-1514:
      loadBalancer:
        servers:
          - address: "10.100.0.2:1514"
    wazuh-secure-tcp:
      loadBalancer:
        servers:
          - address: "10.100.0.2:443"
  routers:
    wazuh-1515:
      rule: "HostSNI(`*`)"
      entryPoints:
        - "wazuh-1515"
      service: "wazuh-1515@file"
    wazuh-1514:
      rule: "HostSNI(`*`)"
      entryPoints:
        - "wazuh-1514"
      service: "wazuh-1514@file"
    wazuh-secure-local-tcp:
      rule: "HostSNI(`wazuh.wiserisk.home`) || HostSNI(`wazuh.wiserisk.be`)"
      entryPoints:
        - "websecure"
      service: "wazuh-secure-tcp@file"
      priority: 2
      tls:
        passthrough: true