http:
  routers:
    wazuh-local:
      rule: "Host(`wazuh.wiserisk.home`) || Host(`wazuh.wiserisk.be`)"
      entryPoints:
        - "web"
      middlewares:
        - "redirect-to-https@file"
      service: "noop@internal"

tcp:
  services:
    wazuh-tcp:
      loadBalancer:
        servers:
          - address: "10.100.0.2:1515"
    wazuh-secure-tcp:
      loadBalancer:
        servers:
          - address: "10.100.0.2:443"
  routers:
    tcp:
      routers:
        wazuh-tcp:
          entryPoints:
            - "wazuh"
          service: "wazuh-tcp@file"
          rule: "HostSNI(`*`)"
          tls:
            passthrough: true
    wazuh-secure-local-tcp:
      rule: "HostSNI(`wazuh.wiserisk.home`) || HostSNI(`wazuh.wiserisk.be`)"
      entryPoints:
        - "websecure"
      service: "wazuh-secure-tcp@file"
      priority: 2
      tls:
        passthrough: true