http:
  services:
    wordpress:
      loadBalancer:
        servers:
          - url: "http://{{ip.wordpress}}:80"
  routers:
    wordpress:
      rule: "Host(`{{domain.wordpress}}`)"
      entryPoints:
        - "web"
      service: "wordpress@file"
      priority: 2
    wordpress-acme:
      rule: "Host(`{{domain.wordpress}}`) && PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - "web"
      service: "wordpress@file"
      priority: 1001

tcp:
  services:
    wordpress-secure-tcp:
      loadBalancer:
        servers:
          - address: "{{ip.wordpress}}:443"
  routers:
    wordpress-secure-tcp:
      rule: "HostSNI(`{{domain.wordpress}}`)"
      entryPoints:
        - "websecure"
      service: "wordpress-secure-tcp@file"
      priority: 2
      tls:
        passthrough: true