http:
  services:
    wordpress:
      loadBalancer:
        servers:
          - url: "http://<WORDPRES_CT_IP>:80"
  routers:
    wordpress:
      rule: "Host(`wordpress.wiserisk.be`)"
      entryPoints:
        - "web"
      service: "wordpress@file"
      priority: 2
    wordpress-acme:
      rule: "Host(`wordpress.wiserisk.be`) && PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - "web"
      service: "wordpress@file"
      priority: 1001

tcp:
  services:
    wordpress-secure-tcp:
      loadBalancer:
        servers:
          - address: "<WORDPRES_CT_IP>:443"
  routers:
    wordpress-secure-tcp:
      rule: "HostSNI(`wordpress.wiserisk.be`)"
      entryPoints:
        - "websecure"
      service: "wordpress-secure-tcp@file"
      priority: 2
      tls:
        passthrough: true
