apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config-github
  namespace: renovate
data:
  config.js: |
    module.exports = {
      platform: 'github',
      token: '<path:k3s/data/renovate#github>',
      onboarding: false,
      requireConfig: 'required',
      repositories: ['amaurydetremerie/HomeLab', 'amaurydetremerie/HLabMonitor', 'amaurydetremerie/HLabMonitor-UI'],
      registryAliases: {
        'docker.io': 'registry.k3s.wiserisk.be',
      },
    };