apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: Kubernetes/K3S/ArgoCD/Manifest
    repoURL: 'https://gitlab.com/amaurydetremerie/HomeLabMirror.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-kustomize
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: Kubernetes/K3S/ArgoCD/Kustomization
    repoURL: 'https://gitlab.com/amaurydetremerie/HomeLabMirror.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: management
    server: 'https://kubernetes.default.svc'
  source:
    path: Kubernetes/K3S/Portainer
    repoURL: 'https://gitlab.com/amaurydetremerie/HomeLabMirror.git'
    targetRevision: HEAD
    plugin: {}
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    path: Kubernetes/K3S/Traefik
    repoURL: 'https://gitlab.com/amaurydetremerie/HomeLabMirror.git'
    targetRevision: HEAD
    plugin: {}
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: Kubernetes/K3S/UptimeKuma
    repoURL: 'https://gitlab.com/amaurydetremerie/HomeLabMirror.git'
    targetRevision: HEAD
    plugin: {}
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: private
    server: 'https://kubernetes.default.svc'
  source:
    path: Kubernetes/K3S/Homepage
    repoURL: 'https://gitlab.com/amaurydetremerie/HomeLabMirror.git'
    targetRevision: HEAD
    plugin: {}
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaresolverr
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: service
    server: 'https://kubernetes.default.svc'
  source:
    path: Kubernetes/K3S/FlareSolverr
    repoURL: 'https://gitlab.com/amaurydetremerie/HomeLabMirror.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: secure
    server: 'https://kubernetes.default.svc'
  source:
    path: Kubernetes/K3S/Vault
    repoURL: 'https://gitlab.com/amaurydetremerie/HomeLabMirror.git'
    targetRevision: HEAD
    plugin: {}
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: system-upgrade
    server: 'https://kubernetes.default.svc'
  source:
    path: Kubernetes/K3S/Upgrade
    repoURL: 'https://gitlab.com/amaurydetremerie/HomeLabMirror.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-db
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: database
    server: 'https://kubernetes.default.svc'
  source:
    path: Kubernetes/K3S/Postgres
    repoURL: 'https://gitlab.com/amaurydetremerie/HomeLabMirror.git'
    targetRevision: HEAD
    plugin: {}
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speedtest-tracker
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: Kubernetes/K3S/SpeedtestTracker
    repoURL: 'https://gitlab.com/amaurydetremerie/HomeLabMirror.git'
    targetRevision: HEAD
    plugin: {}
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: librespeed
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: Kubernetes/K3S/Librespeed
    repoURL: 'https://gitlab.com/amaurydetremerie/HomeLabMirror.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tautulli
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: Kubernetes/K3S/Tautulli
    repoURL: 'https://gitlab.com/amaurydetremerie/HomeLabMirror.git'
    targetRevision: HEAD
    plugin: {}
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2