actions:
  enabled: true

  giteaRootURL: https://git.wiserisk.be
  existingSecret: gitea-runner-secret
  existingSecretKey: registration-token

  global:
    storageClass: local-path

  init:
    image:
      repository: alpine
      tag: "3.19"

  statefulset:
    replicas: 1
    runner:
      config: |
        log:
          level: info
        cache:
          enabled: false
        container:
          require_docker: true
          docker_timeout: 300s
          workdir_parent: /workspace
        runner:
          capacity: 2
          labels:
            - "ubuntu-latest:docker://gitea/runner-images:ubuntu-24.04"
            - "ubuntu-22.04:docker://gitea/runner-images:ubuntu-22.04"
            - "k3s:docker://gitea/runner-images:ubuntu-24.04"