apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "21"
spec:
  project: default
  sources:
    - repoURL: https://SonarSource.github.io/helm-chart-sonarqube
      chart: sonarqube
      targetRevision: 10.7.0
      helm:
        releaseName: sonarqube
        valueFiles:
          - $values/K3S/helm/values/sonarqube.yaml
      plugin:
        name: argocd-vault-plugin-helm
        env:
          - name: AVP_TYPE
            value: vault
          - name: AVP_AUTH_TYPE
            value: k8s
          - name: AVP_K8S_ROLE
            value: argocd
          - name: VAULT_ADDR
            value: http://vault-svc.secure.svc.cluster.local:8200
    - repoURL: https://github.com/amaurydetremerie/HomeLab
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true