apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flaresolverr
  name: flaresolverr
  namespace: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - image: flaresolverr/flaresolverr:latest
          imagePullPolicy: Always
          name: flaresolverr
          ports:
            - containerPort: 8191
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr-svc
spec:
  type: ClusterIP
  selector:
    app: flaresolverr
  ports:
    - port: 8191
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flaresolverr-http
  namespace: service
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    gethomepage.dev/href: "https://flaresolverr.k3s.wiserisk.be"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Flaresolverr
    gethomepage.dev/group: K3S
    gethomepage.dev/icon: flaresolverr.svg
    gethomepage.dev/app: flaresolverr
    gethomepage.dev/name: FlareSolverr
spec:
  rules:
    - host: flaresolverr.k3s.wiserisk.be
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flaresolverr-svc
                port:
                  number: 8191