apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 10.100.0.10
    path: /mnt/Hermes/K3S/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-db-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 10.100.0.10
    path: /mnt/Hermes/K3S/