kind: Secret
apiVersion: v1
metadata:
  name: gitea-homelab-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://git.wiserisk.be/wiserisk/HomeLab.git
  username: wiserisk
  password: <path:k3s/data/gitea#argocd_token>