apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-runner
  namespace: gitea-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-runner
  template:
    metadata:
      labels:
        app: gitea-runner
    spec:
      restartPolicy: Always
      containers:
        - name: runner
          image: gitea/act_runner:latest
          env:
            - name: GITEA_INSTANCE_URL
              value: https://git.wiserisk.be
            - name: GITEA_RUNNER_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitea-runner-secret
                  key: registration-token
            - name: CONFIG_FILE
              value: /etc/act_runner/config.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/act_runner
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: gitea-runner-config
        - name: data
          persistentVolumeClaim:
            claimName: gitea-runner-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-runner-data
  namespace: gitea-runner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
