persistentVolume:
  name: pv-nfs-k3s-postgres
  storage: 50Gi
  accessMode: ReadWriteMany
  nfs:
    server: <path:secrets/data/global#nfs-server>
    path: <path:secrets/data/global#nfs-share>
postgresql:
  global:
    postgresql:
      auth:
        postgresPassword: <path:secrets/data/postgres#mainPassword>
        username: <path:secrets/data/postgres#secondUsername>
        password: <path:secrets/data/postgres#secondPassword>
        database: <path:secrets/data/postgres#secondDatabase>
  primary:
    persistence:
      enabled: true
      volumeName: pvc-nfs-k3s-postgres-volume
      subPath: postgres
      storageClass: nfs
      size: 50Gi
      accessModes:
        - ReadWriteMany
  image:
    debug: true
  readReplicas:
    extraEnvVars:
      - name: BITNAMI_DEBUG
        value: true