[global]
    checkNewVersion = true
    sendAnonymousUsage = true

[api]
    dashboard=true
    debug=true

[log]
    filePath = "/var/log/traefik/traefik.log"
    level = "ERROR"

[accessLog]
    filePath = "/var/log/traefik/access.log"

[providers]
    [providers.file]
        directory="/etc/Homelab/Traefik/traefik_dynamic"
        watch=true

[entryPoints]
    [entryPoints.web]
        address=":80"
    [entryPoints.websecure]
        address=":443"
    [entryPoints.acme]
    [entryPoints.k3s]
        address=":6443"
    [entryPoints.graylog]
        address=":12201/udp"
    [entryPoints.wazuh-1515]
        address=":1515"
    [entryPoints.wazuh-1514]
        address=":1514"
[certificatesResolvers]
    [certificatesResolvers.letsencrypt-ecdsa]
        [certificatesResolvers.letsencrypt-ecdsa.acme]
            caServer = "https://acme-v02.api.letsencrypt.org/directory"
            storage = "/etc/traefik/acme.json"
            keyType = "EC384"
            [certificatesResolvers.letsencrypt-ecdsa.acme.httpChallenge]
                entryPoint = "acme"
            [certificatesResolvers.letsencrypt-ecdsa.acme.tlsChallenge]
    [certificatesResolvers.letsencrypt-rsa2048]
        [certificatesResolvers.letsencrypt-rsa2048.acme]
            caServer = "https://acme-v02.api.letsencrypt.org/directory"
            storage = "/etc/traefik/acme.json"
            keyType = "RSA2048"
            [certificatesResolvers.letsencrypt-rsa2048.acme.httpChallenge]
                entryPoint = "acme"
            [certificatesResolvers.letsencrypt-rsa2048.acme.tlsChallenge]