apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: litellm
  name: litellm
  namespace: litellm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
        - name: litellm
          image: ghcr.io/berriai/litellm:latest
          imagePullPolicy: IfNotPresent
          args: ["--config", "/app/config.yaml", "--port", "4000"]
          ports:
            - containerPort: 4000
          env:
            - name: LITELLM_MASTER_KEY
              value: <path:k3s/data/litellm#master_key>
            - name: OLLAMA_API_KEY
              value: <path:k3s/data/litellm#ollama_api_key>
            - name: OPENROUTER_API_KEY
              value: <path:k3s/data/litellm#openrouter_api_key>
            - name: GEMINI_API_KEY
              value: <path:k3s/data/litellm#gemini_api_key>
            - name: NVIDIA_NIM_API_KEY
              value: <path:k3s/data/litellm#nvidia_nim_api_key>
            - name: OPENAI_API_KEY
              value: <path:k3s/data/litellm#openai_api_key>
            - name: GITHUB_COPILOT_API_KEY
              value: <path:k3s/data/litellm#github_copilot_api_key>
            - name: ONE_MIN_AI_API_KEY
              value: <path:k3s/data/litellm#one_min_ai_api_key>
          volumeMounts:
            - name: litellm-config
              mountPath: /app/config.yaml
              subPath: config.yaml
            - name: litellm-data
              mountPath: /data
              subPath: litellm
      volumes:
        - name: litellm-config
          configMap:
            name: litellm-config
        - name: litellm-data
          persistentVolumeClaim:
            claimName: litellm-pvc
