apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litellm-pvc
  namespace: litellm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
