apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: registry-system
data:
  config.yml: |
    version: 0.1
    log:
      level: info
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
        Access-Control-Allow-Origin: ['https://registry-ui.k3s.wiserisk.be']
        Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS']
        Access-Control-Allow-Credentials: ['true']
    proxy:
      remoteurl: https://registry-1.docker.io
      username: <path:secrets/k3s/docker#username>
      password: <path:secrets/k3s/docker#token>