apiVersion: v1
kind: Secret
metadata:
  name: registry-auth
  namespace: registry-system
type: Opaque
stringData:
  config.yml: |
    version: 0.1
    log:
      level: info
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    proxy:
      remoteurl: https://registry-1.docker.io
      username: <path:secret/data/k3s/registry#docker_username>
      password: <path:secret/data/k3s/registry#docker_password>
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3