apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: registry-system
data:
  config.yml: |
    version: 0.1
    log:
      level: info
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    proxy:
      remoteurl: https://registry-1.docker.io
      username: username
      password: password