apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry-system
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: registry
  selector:
    app: registry