apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-k3s-portainer
  namespace: management
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi