apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-cm
  namespace: private
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: WiseRisk's Home Lab
    base: https://k3s.wiserisk.be/
    favicon: https://github.com/amaurydetremerie/HomeLab/blob/main/assets/logo.png?raw=true
    theme: dark
    color: zinc
    headerStyle: clean
    language: fr
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      hideVisitURL: true
    hideVersion: true
    statusStyle: "dot"
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/amaurydetremerie
        - GitLan:
            - abbr: GL
              href: https://gitlab.com/amaurydetremerie
  services.yaml: |
    - K3S:
        - Traefik:
          icon: traefik.svg
          href: http://10.100.0.201:9000/
          description: K3S Traefik
          widget:
            type: traefik
            url: http://10.100.0.201:9000/
    - LXC:
        - Traefik:
          icon: traefik.svg
          href: https://traefik.wiserisk.be/
          description: Traefik Principal
          widget:
            type: traefik
            url: https://traefik.wiserisk.be/
            username: <path:secrets/data/traefik#username>
            password: <path:secrets/data/traefik#password>
        - Nextcloud:
          icon: nextcloud-blue.svg
          href: https://nextcloud.wiserisk.be/
          description: Traefik Principal
          widget:
            type: nextcloud
            url: https://nextcloud.wiserisk.be/
            username: <path:secrets/data/nextcloud#password>
            password: <path:secrets/data/nextcloud#password>
        - Plex:
          icon: plex.svg
          href: https://plex.wiserisk.be/
          description: Traefik Principal
          widget:
            type: plex
            url: https://plex.wiserisk.be/
            key: <path:secrets/data/plex#token>
        - Swizzin:
          href: https://seedbox.wiserisk.be/
          description: Traefik Principal
        - AdGuard:
          icon: adguard-home.svg
          href: http://10.0.0.86/
          description: AdGuard
          widget:
            type: adguard
            url: http://10.0.0.86/
            username: <path:secrets/data/adguard#username>
            password: <path:secrets/data/adguard#password>
    - VM:
        - TrueNas:
            href: https://nas.wiserisk.be/
            description: Truenas
            widget:
              type: truenas
              url: https://nas.wiserisk.be/
              key: <path:secrets/data/truenas#api-key>
        - HomeAssistant:
            href: https://ha.wiserisk.be/
            description: Home Assistant
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: google
        target: _blank
  docker.yaml: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage-sa
  namespace: private
  labels:
    app.kubernetes.io/name: homepage
secrets:
  - name: homepage-secret
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage-secret
  namespace: private
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage-cr
  labels:
    app.kubernetes.io/name: homepage
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage-rb
  labels:
    app.kubernetes.io/name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage-cr
subjects:
  - kind: ServiceAccount
    name: homepage-sa
    namespace: private
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: private
  labels:
    app.kubernetes.io/name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage-sa
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:v0.8.13"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: homepage-cm-volume
              mountPath: /app/config/custom.js
              subPath: custom.js
            - name: homepage-cm-volume
              mountPath: /app/config/custom.css
              subPath: custom.css
            - name: homepage-cm-volume
              mountPath: /app/config/bookmarks.yaml
              subPath: bookmarks.yaml
            - name: homepage-cm-volume
              mountPath: /app/config/docker.yaml
              subPath: docker.yaml
            - name: homepage-cm-volume
              mountPath: /app/config/kubernetes.yaml
              subPath: kubernetes.yaml
            - name: homepage-cm-volume
              mountPath: /app/config/services.yaml
              subPath: services.yaml
            - name: homepage-cm-volume
              mountPath: /app/config/settings.yaml
              subPath: settings.yaml
            - name: homepage-cm-volume
              mountPath: /app/config/widgets.yaml
              subPath: widgets.yaml
            - name: homepage-logs-volume
              mountPath: /app/config/logs
      volumes:
        - name: homepage-cm-volume
          configMap:
            name: homepage-cm
        - name: homepage-logs-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: homepage-svc
  namespace: private
  labels:
    app.kubernetes.io/name: homepage
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app.kubernetes.io/name: homepage
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-http
  namespace: private
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: k3s.wiserisk.be
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage-svc
                port:
                  number: 3000