mail: XXX
ip:
  wordpress: 255.255.255.255
  truenas: 255.255.255.255
  traefik: 255.255.255.255
  swizzin: 255.255.255.255
  portainer: 255.255.255.255
  plex: 255.255.255.255
  nextcloud: 255.255.255.255
  k3s:
    1: 255.255.255.255
    2: 255.255.255.255
    3: 255.255.255.255
  home-assistant: 255.255.255.255
  pve:
    1: 255.255.255.255
    2: 255.255.255.255
    3: 255.255.255.255
  coolify: 255.255.255.255
domain:
  wordpress: wordpress.domain.com
  truenas: truenas.domain.com
  traefik: traefik.domain.com
  swizzin: swizzin.domain.com
  portainer: portainer.domain.com
  plex: plex.domain.com
  nextcloud: nextcloud.domain.com
  k3s: k3s.domain.com
  home-assistant: home-assistant.domain.com
  pve: pve.domain.com
  coolify: coolify.domain.com
nfs:
  k3s: /mnt/pool/k3s
security:
  basic-auth: xx:xx:xx