apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'discord'
      routes:
        - match:
            severity: critical
          receiver: 'discord'
          group_wait: 10s
    receivers:
      - name: 'discord'
        webhook_configs:
          - url: <path:k3s/data/monitoring#discord>
            send_resolved: true