apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: 'discord'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      routes:
        - match:
            severity: critical
          receiver: 'discord'
          group_wait: 10s
        - match:
            severity: warning
          receiver: 'discord'
          group_wait: 30s
        - match:
            alertname: myalert
          receiver: 'discord'
          group_wait: 1s
    receivers:
      - name: discord
        webhook_configs:
          - send_resolved: true
            url: 'http://alermanager-discord-svc:9099'