apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-templates
  namespace: monitoring
data:
  discord.tmpl: |
    {{ define "discord.default.message" }}
    {{ if gt (len .Alerts.Firing) 0 }}
    :red_circle: **Alertes en cours**
    {{ range .Alerts }}
    **Alerte:** {{ .Labels.alertname }}
    **Sévérité:** {{ .Labels.severity }}
    **Description:** {{ .Annotations.description }}
    {{ end }}
    {{ end }}
    {{ if gt (len .Alerts.Resolved) 0 }}
    :green_circle: **Alertes résolues**
    {{ range .Alerts }}
    **Alerte:** {{ .Labels.alertname }}
    {{ end }}
    {{ end }}
    {{ end }}