apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-ipc-lock
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-ipc-lock
subjects:
  - kind: ServiceAccount
    name: vault-sa
    namespace: secure