apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: secure
data:
  config.hcl: |
    ui = true
    disable_mlock = true
    storage "file" {
      path = "/vault/data"
    }
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }