apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: secure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault-sa
      initContainers:
        - name: config-init
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              # Créer un répertoire de configuration modifiable
              mkdir -p /tmp/vault/config
              cp /vault/original-config/config.hcl /tmp/vault/config/config.hcl
              # Créer les répertoires nécessaires avec les bonnes permissions
              mkdir -p /vault/data
              mkdir -p /vault/secrets
          volumeMounts:
            - name: vault-config
              mountPath: /vault/original-config
            - name: vault-config-working
              mountPath: /tmp/vault/config
            - name: vault-data
              mountPath: /vault/data
            - name: vault-secrets
              mountPath: /vault/secrets
          securityContext:
            runAsUser: 0
      containers:
        - name: vault
          image: hashicorp/vault:1.15.4
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              ./vault/scripts/vault-unseal.sh &
              cp /tmp/vault/config/config.hcl /vault/config/config.hcl
              vault server -config=/vault/config/config.hcl
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_ADDR
              value: http://127.0.0.1:8200
            - name: VAULT_API_ADDR
              value: https://vault.k3s.wiserisk.be
          volumeMounts:
            - name: vault-config-working
              mountPath: /tmp/vault/config
            - name: vault-config
              mountPath: /vault/config
            - name: vault-data
              mountPath: /vault/data
            - name: unseal-data
              mountPath: /vault/unseal
              subPath: unseal
            - name: vault-secrets
              mountPath: /vault/secrets
            - name: vault-unseal-script
              mountPath: /vault/scripts
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
            runAsUser: 0
      volumes:
        - name: vault-config
          configMap:
            name: vault-config
        - name: vault-config-working
          emptyDir: {}
        - name: vault-data
          persistentVolumeClaim:
            claimName: vault-pvc
        - name: unseal-data
          persistentVolumeClaim:
            claimName: unseal-pvc
        - name: vault-secrets
          emptyDir: {}
        - name: vault-unseal-script
          configMap:
            name: vault-auto-unseal
            defaultMode: 0755