apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: secure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault-sa
      containers:
        - name: vault
          image: hashicorp/vault:1.15.4
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true  # Ajouter les privilèges nécessaires
            capabilities:
              add:
                - IPC_LOCK  # Conserver la capacité IPC_LOCK
            runAsUser: 0  # Exécuter en root si nécessaire
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_ADDR
              value: http://127.0.0.1:8200
            - name: VAULT_API_ADDR
              value: https://vault.k3s.wiserisk.be
          volumeMounts:
            - name: vault-data
              mountPath: /vault/data
            - name: vault-config
              mountPath: /vault/config
      volumes:
        - name: vault-data
          persistentVolumeClaim:
            claimName: vault-pvc
        - name: vault-config
          configMap:
            name: vault-config