apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-secure-k3s-vault
  namespace: secure
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs