apiVersion: v1
kind: Service
metadata:
  name: vault-svc
  namespace: secure
  labels:
    app: vault
spec:
  selector:
    app: vault
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
  type: ClusterIP