apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-auto-unseal
  namespace: secure
data:
  vault-unseal.sh: |
    #!/bin/sh
    while ! vault status > /dev/null 2>&1; do
      echo "En attente du démarrage de Vault..."
      sleep 5
    done

    UNSEAL_KEY1=$(cat /vault/unseal/unseal-key-1)
    UNSEAL_KEY2=$(cat /vault/unseal/unseal-key-2)
    UNSEAL_KEY3=$(cat /vault/unseal/unseal-key-3)

    vault operator unseal $UNSEAL_KEY1
    vault operator unseal $UNSEAL_KEY2
    vault operator unseal $UNSEAL_KEY3
    
    umount /vault/unseal
    umount /vault/scripts