apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaresolverr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd-image-updater.argoproj.io/image-list: flaresolverr=flaresolverr/flaresolverr
    argocd-image-updater.argoproj.io/flaresolverr.update-strategy: latest
    argocd-image-updater.argoproj.io/flaresolverr.allow-tags: latest
spec:
  project: default
  source:
    repoURL: https://github.com/amaurydetremerie/HomeLab.git
    targetRevision: HEAD
    path: K3S/tools/flaresolverr
  destination:
    server: https://kubernetes.default.svc
    namespace: flaresolverr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true