apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-system
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://git.wiserisk.be/adetremerie/HomeLab.git
    targetRevision: HEAD
    path: K3S/infrastructure/kube-system
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true