apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://git.wiserisk.be/wiserisk/HomeLab.git
    targetRevision: HEAD
    path: K3S/tools/open-webui
  destination:
    server: https://kubernetes.default.svc
    namespace: open-webui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true