apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxmox-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxmox-exporter
  template:
    metadata:
      labels:
        app: proxmox-exporter
    spec:
      containers:
        - name: proxmox-exporter
          image: prompve/prometheus-pve-exporter:3.5.2
          ports:
            - containerPort: 9221
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
      volumes:
        - name: config
          configMap:
            name: proxmox-exporter-config