apiVersion: v1
kind: Service
metadata:
  name: proxmox-exporter
  namespace: monitoring
spec:
  selector:
    app: proxmox-exporter
  ports:
    - protocol: TCP
      port: 9221
      targetPort: 9221
  type: ClusterIP