http:
  services:
    unbound-status:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9091"

  routers:
    unbound-status-secure:
      rule: "Host(`unbound.vps.wiserisk.be`)"
      entryPoints:
        - websecure
      middlewares:
        - authelia@file
        - security@file
        - compression@file
      service: unbound-status@file
      tls:
        certResolver: letsencrypt-ovh