version: "3.8"

services:
  heimdall:
    container_name: Heimdall
    image: lscr.io/linuxserver/heimdall:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.heimdall.rule=Host(`dashboard.portainer.wiserisk.be`)
      - traefik.http.routers.heimdall.entrypoints=websecure
      - traefik.http.services.heimdall.loadbalancer.server.port=80
      - traefik.http.routers.heimdall.service=heimdall
      - traefik.http.routers.heimdall.tls.certresolver=leresolver
    environment:
      - TZ=Europe/Brussels
    volumes:
      - heimdall:/config
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  heimdall:
    external: true