---
- name: Create LXC containers
  community.general.proxmox:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ item.vmid }}"
    hostname: "{{ item.hostname }}"
    description: "{{ item.description | default('') }}"
    cores: "{{ item.cores | default(1) }}"
    memory: "{{ item.memory | default(512) }}"
    swap: "{{ item.swap | default(0) }}"
    storage: "{{ proxmox_storage }}"
    disk: "{{ item.disk | default(8) }}"
    ostemplate: "{{ item.ostemplate | default(proxmox_lxc_ostemplate) }}"
    netif: "{{ item.netif }}"
    mounts: "{{ item.mounts | default(omit) }}"
    unprivileged: "{{ item.unprivileged | default(true) }}"
    features: "{{ item.features | default([]) }}"
    startup: "{{ item.startup | default(omit) }}"
    onboot: "{{ item.onboot | default(true) }}"
    state: present
  loop: "{{ proxmox_lxc }}"
  loop_control:
    label: "{{ item.hostname }} (vmid={{ item.vmid }})"