---
- name: Download LXC OS template
  community.general.proxmox_template:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    node: "{{ proxmox_node }}"
    storage: local
    template: "{{ proxmox_lxc_ostemplate | split(':') | last | split('/') | last }}"
    content_type: vztmpl
    state: present
  when: proxmox_lxc | length > 0