---
- name: Create VMs
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ item.vmid }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default('') }}"
    cores: "{{ item.cores | default(2) }}"
    sockets: "{{ item.sockets | default(1) }}"
    cpu: "{{ item.cpu | default('host') }}"
    memory: "{{ item.memory | default(2048) }}"
    balloon: "{{ item.balloon | default(0) }}"
    bios: "{{ item.bios | default('seabios') }}"
    machine: "{{ item.machine | default('q35') }}"
    scsihw: "{{ item.scsihw | default('virtio-scsi-single') }}"
    agent: "{{ item.agent | default(1) }}"
    numa_enabled: "{{ item.numa | default(false) }}"
    ostype: "{{ item.ostype | default('l26') }}"
    net: "{{ item.net }}"
    boot: "{{ item.boot | default('order=scsi0;net0') }}"
    scsi: "{{ item.scsi | default(omit) }}"
    ide: "{{ item.ide | default(omit) }}"
    efidisk0: "{{ item.efidisk0 | default(omit) }}"
    usb: "{{ item.usb | default(omit) }}"
    localtime: "{{ item.localtime | default(omit) }}"
    tablet: "{{ item.tablet | default(omit) }}"
    onboot: "{{ item.onboot | default(true) }}"
    startup: "{{ item.startup | default(omit) }}"
    state: present
  loop: "{{ proxmox_vms }}"
  loop_control:
    label: "{{ item.name }} (vmid={{ item.vmid }})"