apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-k3s-traefik
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: <path:secrets/data/global#nfs-server>
    path: <path:secrets/data/global#nfs-share>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-k3s-traefik
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 200Mi
---
# Need to be located at /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--entryPoints.acme"
      - "--certificatesResolvers.letsencrypt-ecdsa.acme.email=<path:secrets/data/global#mail>"
      - "--certificatesResolvers.letsencrypt-ecdsa.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.letsencrypt-ecdsa.acme.storage=/data/acme.json"
      - "--certificatesResolvers.letsencrypt-ecdsa.acme.keyType=EC384"
      - "--certificatesResolvers.letsencrypt-ecdsa.acme.httpChallenge.entryPoint=acme"
      - "--certificatesResolvers.letsencrypt-ecdsa.acme.tlsChallenge=true"
      - "--certificatesResolvers.letsencrypt-rsa2048.acme.email=<path:secrets/data/global#mail>"
      - "--certificatesResolvers.letsencrypt-rsa2048.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.letsencrypt-rsa2048.acme.storage=/data/acme.json"
      - "--certificatesResolvers.letsencrypt-rsa2048.acme.keyType=RSA2048"
      - "--certificatesResolvers.letsencrypt-rsa2048.acme.httpChallenge.entryPoint=acme"
      - "--certificatesResolvers.letsencrypt-rsa2048.acme.tlsChallenge=true"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.web.http.redirections.entryPoint.permanent=true"
      - "--entrypoints.web.http.redirections.entryPoint.to=:443"
      - "--entryPoints.websecure.http.tls.certResolver=letsencrypt-ecdsa"
    ports:
      traefik:
        expose: true
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    persistence:
      enabled: true
      name: data
      existingClaim: pvc-nfs-k3s-traefik
      accessMode: ReadWriteMany
      size: 200Mi
      storageClass: nfs
      volumeName: pvc-nfs-k3s-traefik-volume
      path: /data
      subPath: traefik
