apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  namespace: graylog-stack
spec:
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - k3s-worker-02
      volumes:
        - name: graylog-volume
          persistentVolumeClaim:
            claimName: graylog-pvc
        - name: graylog-config-volume
          configMap:
            name: graylog-config
      containers:
        - name: graylog
          image: graylog/graylog:6.1.5
          env:
            - name: GRAYLOG_PASSWORD_SECRET
              value: <path:k3s/data/graylog-stack#password>
            - name: GRAYLOG_ROOT_PASSWORD_SHA2
              value: <path:k3s/data/graylog-stack#password-root>
            - name: GRAYLOG_HTTP_EXTERNAL_URI
              value: "https://graylog.k3s.wiserisk.be/"
            - name: GRAYLOG_ELASTICSEARCH_HOSTS
              value: "http://elasticsearch-svc.graylog-stack.svc.cluster.local:9200"
            - name: GRAYLOG_MONGODB_URI
              value: "mongodb://mongodb-svc.graylog-stack.svc.cluster.local:27017/graylog"
          ports:
            - containerPort: 9000
            - containerPort: 12201
            - containerPort: 12201
              protocol: UDP
          volumeMounts:
            - name: graylog-volume
              mountPath: /usr/share/graylog/data
              subPath: graylog
            - name: graylog-config-volume
              mountPath: /usr/share/graylog/data/config