apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: graylog-udp
  namespace: graylog-stack
spec:
  entryPoints:
    - graylog
  routes:
    - services:
        - name: graylog-udp-svc
          port: 12201