apiVersion: v1
kind: PersistentVolume
metadata:
  name: graylog-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 10.100.0.10
    path: /mnt/Hermes/K3S