name: WebHookTraefik

on:
  push:
    paths:
      - Traefik/**
  delete:
    paths:
      - Traefik/**

jobs:
  update_traefik_principal:
    runs-on: ubuntu-latest
      steps:
      - name: Retrieve secrets from Vault
        id: vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          role_id: ${{ secrets.VAULT_ROLE_ID }}
          secret_id: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secrets/data/webhook secret;
            secrets/data/traefik auth;
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
          VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}

      - name: Call pull
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}/hooks/pull-webhook
          webhook_secret: ${{ steps.vault.outputs.secret }}
          webhook_auth_type: "basic"
          webhook_auth: ${{ steps.vault.outputs.auth }}
          data: '{ "project": "traefik" }'
      - name: Call restart
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}/hooks/restart-webhook
          webhook_secret: ${{ steps.vault.outputs.secret }}
          webhook_auth_type: "basic"
          webhook_auth: ${{ steps.vault.outputs.auth }}
          data: '{ "service": "traefik" }'