name: WebHookTraefik

on:
  push:
    paths:
      - Webhook/**
  delete:
    paths:
      - Webhook/**

jobs:
  update_traefik_principal:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Call pull
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}/hooks/pull-webhook
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth_type: "basic"
          webhook_auth: ${{ secrets.BASIC_AUTH }}
          data: '{ "project": "webhook" }'