name: WebHookWebHook

on:
  push:
    paths:
      - Webhook/**
  delete:
    paths:
      - Webhook/**

jobs:
  update_webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve secrets from Vault
        id: vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secrets/data/webhook secret;
            secrets/data/traefik auth;

      - name: Call pull
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}/hooks/pull-webhook
          webhook_secret: ${{ steps.vault.outputs.secret }}
          webhook_auth_type: "basic"
          webhook_auth: ${{ steps.vault.outputs.auth }}
          data: '{ "project": "webhook" }'
