name: WebHookWebHook

on:
  push:
    paths:
      - Webhook/**
  delete:
    paths:
      - Webhook/**

jobs:
  update_webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Bypass Cloudflare for GitHub Action
        uses: xiaotianxt/bypass-cloudflare-for-github-action@v1.0.0
        with:
          cf_zone_id: ${{ secrets.CF_ZONE_ID }}
          cf_api_key: ${{ secrets.CF_API_KEY }}

      - name: Retrieve secrets from Vault
        id: vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: github
          githubToken: ${{ secrets.VAULT_GITHUB_TOKEN }}
          secrets: |
            k3s/data/webhook secret;
            k3s/data/global basic_username;
            k3s/data/global basic_password;

      - name: Call pull
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}/hooks/pull-webhook
          webhook_secret: ${{ steps.vault.outputs.secret }}
          webhook_auth_type: "basic"
          webhook_auth: ${{ format('{0}:{1}', steps.vault.outputs.username, steps.vault.outputs.password) }}
          data: '{ "project": "webhook" }'
      - name: Call restart
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}/hooks/restart-webhook
          webhook_secret: ${{ steps.vault.outputs.secret }}
          webhook_auth_type: "basic"
          webhook_auth: ${{ format('{0}:{1}', steps.vault.outputs.basic_username, steps.vault.outputs.basic_password) }}
          data: '{ "service": "webhook" }'
